name: Aetherium

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-encoder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install 1/2
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install 2/2
        run: |
          pip install requests cryptography || true

      - name: Generate
        env:
          key1: ${{ secrets.key1 }}
        run: |
          python encoder.py --key1 "$key1" || true

      - name: Upload
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add docs/TG-AS_Aetherium-* 2>/dev/null || true

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Auto-update Aetherium docs"
            git push
          fi
